apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-authentication-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-authentication-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-authentication-service
    spec:
      containers:
        - name: authentication-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.clusterIP.port }}