apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-authentication-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-authentication-service
  ports:
    - port: {{ .Values.service.clusterIP.port }}
      targetPort: {{ .Values.service.clusterIP.port }}
