apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-authentication-service-nodeport
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}-authentication-service
  ports:
    - port: {{ .Values.service.nodePort.port }}
      targetPort: {{ .Values.service.nodePort.port }}
      nodePort: {{ .Values.service.nodePort.nodePort }}
